apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ../../components/routes

patches:
  - path: patch-remove-dashboard.yaml
  - path: patch-gateway-only.yaml
