FROM registry.access.redhat.com/ubi9/python-312:latest

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app ./app
COPY gateways ./gateways
COPY vllm-email-gw.json ./vllm-email-gw.json

EXPOSE 8080 3025

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8080"]
